Added handling and counters for filename, http, and time errors
Cobertos/notion_export_enhancer pull request #2
Opened 2021-03-21 08:12 UTC by KGBicheno

I've added extra error-handling for:
 - Situations where a block's parent returns NoneType. If so, it now checks for a valid child element to replace it and fails that block if none are found. The program will, however, continue past that block.
 - Some blocks were returning a HTTPError in the Notion API through client.py at the point where enhancer.py tried to load the block using NotionID. An error at this point will now fail that block but allow for the program to continue.
 - The creation of the Zip file was failing in situations where the lastEditedTime tuple returned a NoneType error. I attempted to have the program replace missing create times with edited times and vice versa, but the issue was with the tuple, and I couldn't see where the error was being introduced. The block will still load, but with the default (1980, 1, 1, 0, 0, 0) timestamp attached.

The final output will now include the number of times any of these errors occurred.

2021-03-21 09:22 UTC, Cobertos approved these changes

2021-03-21 09:22 UTC, Cobertos commented on notion_export_enhancer/enhancer.py
> +              zi = zipfile.ZipInfo(newPath, date_time=(1980,1,1,0,0,0))
Hmm, I think it would be preferable here to:
* Print out an error including the `newPath`. Gives the user a bit more info than simple the amount of this type of error that occured, and keeps the logic more localized to where the error occured.
* `date_time` should instead be the original date on the file in the exported data zip, maybe? I do like the idea of setting it to 1980 as effectively a marker that "Hey, this date was actually not able to be exported properly." What do you think?

2021-03-21 09:22 UTC, Cobertos commented on notion_export_enhancer/enhancer.py
> +    error_count['ClientHTTP'] += 1
Any idea what type of HTTP error was being experienced?

If it was just Notion timing out, ideally we'd have some sort of backoff + retry algorithm here (using an off-the-shelf backoff library like https://pypi.org/project/backoff/) to make it a bit more robust.

This probably works fine for now though.

2021-03-21 09:22 UTC, Cobertos commented on notion_export_enhancer/enhancer.py
> +          if isinstance(pageBlock, Block):
I don't think this work as expected? For the rest of the function, pageBlock is meant to be a `PageBlock` type. So it can do

* `pageBlock.icon` additions to the name
* `pageBlock._get_record_data()["created_time"]` time retrieval (though I think all blocks might have time, I'm just not sure if they're stored in the notion-py record the same)
* `pageBlock.title` retruncation (though it only occurs if the original length was 50 characters)

If we're going to choose a non-PageBlock to base renames on, we should:

* Remove the while loop
* Check to see if pageBlock.parent exists _without_ setting pageBlock (doesn't need to do traversal up the parent chain anymore). Using `hasattr() and is not None` would be cleaner than a try/catch though
* Do the child search
* Then if all this results in a non-PageBlock, break early without doing the .icon and .title retruncation stuff

2021-03-21 09:23 UTC, Cobertos requested changes
Woops, meant to hit 'Request changes'

2021-03-21 11:18 UTC, KGBicheno commented on notion_export_enhancer/enhancer.py
> +              zi = zipfile.ZipInfo(newPath, date_time=(1980,1,1,0,0,0))
I like it, maybe it could print the error, the newpath, and give the user the choice of:
 1. Use zip-file date
 2. Use default date (for later change)
 3. Enter custom date
 4. Skip block

Also, any records/blocks that get skipped get some form of identifier logged in a file.

2021-03-21 11:18 UTC, KGBicheno commented on notion_export_enhancer/enhancer.py
> +    error_count['ClientHTTP'] += 1
I'll slot a retry line in and see if that fixes it, if not, I'll put a backoff in as well.

2021-03-21 11:18 UTC, KGBicheno commented on notion_export_enhancer/enhancer.py
> +          if isinstance(pageBlock, Block):
Yeah, my bad, I meant to use the base Block class there and then morph it into PageBlock before the rest of it, and then forgot to do the morph. 

Your solution is much simpler and would be closer to what the user expects; I doubt the objects causing this error are ones that would contain user-created data.

2021-03-21 19:11 UTC, KGBicheno commented
There's a bug where hitting enter without an input will still loop the question, but it will crash no matter what you enter next. Otherwise it's fine. Run through 3.6.8 as per instructions.

Pushed mainly to show you where I got up to. I'm going to redo the whole thing in a day or two. It would probably be easier to add a flag for setting the options at the start - I had hundreds of inputs from my Notion pages. :D Thanks for letting me have a go! :dancers:

2021-03-22 12:36 UTC, Cobertos commented on notion_export_enhancer/enhancer.py
> +              zi = zipfile.ZipInfo(newPath, date_time=(1980,1,1,0,0,0))
Sounds like a lot of complexity, which I'd like to minimize to make it easier for end-users to expect what will happen when running, but also to keep maintenance and unit tests easier.

Ideally this case should never happen, `noteNameRewrite()` should always return a proper `lastEditedTime`. Maybe if it chooses a non-PageBlock this wont work though.

We could add a CLI command to set default date (and then the user can set it to 1980-1-1 00:00:00 if they want)? Something like `--default-date=[ISO8601 string]`, and if it's omitted it will basically just use the stat mtime of `realPath` in that scope.

2021-03-22 12:42 UTC, Cobertos commented on notion_export_enhancer/enhancer.py
> +          if isinstance(pageBlock, Block):
The IDs in the export should all map to real user created blocks, unless maybe the user has since deleted a block. Didn't think about that.

Now that I think about this, the block fetching by ID is the most brittle portion of this code, there's no judging what will come from Notion. Trying a couple heuristics like we are and logging out an error is the best we can do, then recover from it as best we can.

2021-07-14 10:37 UTC, Cobertos commented
Going to close this one, I merged a couple things from here into https://github.com/Cobertos/notion_export_enhancer/commit/8c72109d44e356287c680b76be2e96a5bcc40dfc

Thanks again for the work and sorry I haven't been more communicative! This just hasn't been a priority for me

2021-07-14 10:37 UTC, closed without merging